version: '3'
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: js
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgresPass

  game-publisher:
    build: ./microservices/game_publisher
    ports:
      - "3000:3000"
    volumes:
      - ./microservices/shared/database:/usr/src/app/src/database
      - ./microservices/shared/models:/usr/src/app/src/models
    depends_on:
      - postgres
      - redis

  bet-api:
    build: ./microservices/bet_api
    ports:
      - "3001:3000"
    volumes:
      - ./microservices/shared/database:/usr/src/app/src/database
      - ./microservices/shared/models:/usr/src/app/src/models
    depends_on:
      - postgres

  replay-api:
    build: ./microservices/replay_api
    ports:
      - "3002:3000"
    volumes:
      - ./microservices/shared/database:/usr/src/app/src/database
      - ./microservices/shared/models:/usr/src/app/src/models
    depends_on:
      - postgres

  notification-worker:
    build: ./microservices/notification_worker
    volumes:
      - ./microservices/shared/database:/usr/src/app/src/database
      - ./microservices/shared/models:/usr/src/app/src/models
    depends_on:
      - postgres
      - game-publisher
      - redis

  favorite-api:
    build: ./microservices/favorite_api
    ports:
      - "3004:3000"
    volumes:
      - ./microservices/shared/database:/usr/src/app/src/database
      - ./microservices/shared/models:/usr/src/app/src/models
    depends_on:
      - postgres
      - game-publisher
