FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY . .

# Install any test dependencies if necessary
RUN npm install jest supertest

# Default command to run tests
CMD ["npm", "test"]